### PR TITLE
Add International date format support

### PR DESCRIPTION
**Pull request by godban**
Hey there, thx for a nice package. As European user, I want to have possibility declare dates in European format `DD-MM-YYYY`. This PR extends Date regex with it.

### CODE REVIEW

**Comment by ungoldman** [comment]
Hi @godban, thanks for the PR! Since there are a lot of variations of date formats, maybe we should go with the most permissive, which I think would be

1-4 numbers, delimiter (`-`,`.`,`/`), 1-2 numbers, delimiter, 1-4 numbers

That way all the following would be valid dates:

2018-04-16
16.04.2018
4/16/18

What do you think?

**Comment by godban** [comment]
@ungoldman yea, make sense. Updated

**Comment by godban** [comment]
so... what's up, Doc?

**Comment by ungoldman** [comment]
Hi @godban. Sorry I've been busy. Looks good enough, thanks.

**Comment by ungoldman** [comment]
📦 [`2.5.0`](https://github.com/hypermodules/changelog-parser/releases/tag/v2.5.0)

**Pull request merged**
