### PR TITLE
Add promise support

### PR DESCRIPTION
**Pull request by jrmykolyn**
@ungoldman 

Notes:
- Implementation of featured requested in issue #18
- Production code updated (new functionality added, existing functionality unaffected).
- Code style passes linter.
- Tests updated and passing.
- `README.md` updated.

### CODE REVIEW

**Comment by ungoldman** [comment]
@jrmykolyn looks like tests are not passing on CI, may just be a style thing. Running `npm test` locally should tell you what to fix.

Looks like there are some significant changes to the core logic here, I'll pull it down when I have a moment in the next couple of days and make sure there are no breaking changes.

FYI the primary consumer of this package is [`gh-release`](https://github.com/hypermodules/gh-release), which is used internally by a handful of companies and in a modest amount of open source projects too. I'll test that your changes don't affect that module's use, and if that works fine I see no problem with adding this functionality. Thanks for taking the initiative!

**Comment by jrmykolyn** [comment]
@ungoldman 

Whoops, looks like I forgot to run the linter a final time before submitting the PR. Outstanding code style issues fixed and pushed to PR branch.

Thanks for considering this. Let me know if there's anything else you'd like me to clarify/fix?

**Comment by jrmykolyn** [comment]
@ungoldman Hey there. Any movement on the review? Happy to help out if possible?

**Comment by ungoldman** [comment]
@jrmykolyn tested locally, looks good, works fine with `gh-release` too. Thanks!

**Comment by ungoldman** [comment]
@jrmykolyn released in [v2.2.0](https://github.com/hypermodules/changelog-parser/releases/tag/v2.2.0)

**Pull request merged**
